package net.runelite.client.plugins.logger;

public interface LogEntry {

    String LOGGED_IN = "LOGGED_IN";
    String LOGGED_OUT = "LOGGED_OUT";

    String MOUSE_CLICKED = "MOUSE_CLICKED";
    String MOUSE_PRESSED = "MOUSE_PRESSED";
    String MOUSE_DRAGGED = "MOUSE_DRAGGED";
    String MOUSE_RELEASED = "MOUSE_RELEASED";
    String MOUSE_MOVED = "MOUSE_MOVED";
    String MOUSE_EXITED = "MOUSE_EXITED";
    String MOUSE_ENTERED = "MOUSE_ENTERED";

    String KEY_PRESSED = "KEY_PRESSED";
    String KEY_RELEASED = "KEY_RELEASED";
    String KEY_TYPED = "KEY_TYPED";

    String FOCUS_GAINED = "FOCUS_GAINED";
    String FOCUS_LOST = "FOCUS_LOST";

    String PLAYER_MOVED = "PLAYER_MOVED";
    String PLAYER_SPAWNED = "PLAYER_SPAWNED";
    String PLAYER_DESPAWNED = "PLAYER_DESPAWNED";
    String PLAYER_ANIMATION_CHANGED = "PLAYER_ANIMATION_CHANGED";

    String NPC_MOVED = "NPC_MOVED";
    String NPC_ANIMATION_CHANGED = "NPC_ANIMATION_CHANGED";
    String NPC_SPAWNED = "NPC_SPAWNED";
    String NPC_DESPAWNED = "NPC_DESPAWNED";

    String GAMEOBJECT_SPAWNED = "GAMEOBJECT_SPAWNED";
    String WIDGET_LOADED = "WIDGET_LOADED";

    String GROUND_ITEM_SPAWNED = "GROUND_ITEM_SPAWNED";
    String GROUND_ITEM_DESPAWNED = "GROUND_ITEM_DESPAWNED";

    String ITEM_CONTAINER_CHANGED = "ITEM_CONTAINER_CHANGED";

    String MENU_ACTION_CLICKED = "MENU_ACTION_CLICKED";

    String RUN_ENERGY_CHANGED = "RUN_ENERGY_CHANGED";
    String HEALTH_CHANGED = "HEALTH_CHANGED";
    String PRAYER_CHANGED = "PRAYER_CHANGED";
    String SPECIAL_ATTACK_CHANGED = "SPECIAL_ATTACK_CHANGED";

    String RUN_ENERGY_ENABLED = "RUN_ENERGY_ENABLED";
    String RUN_ENERGY_DISABLED = "RUN_ENERGY_DISABLED";
    String SPECIAL_ATTACK_ENABLED = "SPECIAL_ATTACK_ENABLED";
    String SPECIAL_ATTACK_DISABLED = "SPECIAL_ATTACK_DISABLED";

    String XP_GAINED = "XP_GAINED";
    String LEVEL_GAINED = "LEVEL_GAINED";

    // Camera pitch and yaw changes.

}
